server:
  port: 9003

spring:
  application:
    name: CERTIFICATION_SERVICE

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.management.ua.amqp.KafkaValueSerializer
      client-id: id
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: id
      value-deserializer: io.management.ua.amqp.KafkaValueDeserializer

  redis:
    host: localhost
    port: 6379
    database: 0