server:
  port: 9003

spring:
  application:
    name: CERTIFICATION_SERVICE

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:migration
    out-of-order: true
    baseline-on-migrate: true
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.management.ua.amqp.KafkaValueSerializer
      client-id: id
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: id
      value-deserializer: io.management.ua.amqp.KafkaValueDeserializer

  redis:
    host: localhost
    port: 6379
    database: 0